#################################
# Core Performance & Backend
#################################
backend = "glx";
vsync = true;
use-damage = true;
glx-no-stencil = true;
unredir-if-possible = true;

#################################
# Disable Expensive Effects
#################################
corner-radius = 0;
shadow = false;
fading = false;

#################################
# Kitty Opacity
#################################
opacity-rule = [
  "85:class_g = 'kitty'"
];

#################################
# Window Types
#################################
wintypes:
{
  tooltip = { shadow = false; };
  popup_menu = {};
  dropdown_menu = {};
};
